### ISSUE TITLE
Included Hbb process fails on call to installLHAPDF6

### ISSUE THREAD

**Issue by JasonNielsen** [scipp-atlas/mapyde#101]
I tried to run the included Hbb process with the simplest possible TOML steering file (basically a copy of the `user.toml` file).

The `madgraph` job failed with the following error:

```
1 processes with 4 diagrams generated in 0.277 s
Total: 1 processes with 4 diagrams
output PROC_madgraph
First output using loop matrix-elements has been detected. Now asking for loop reduction:
For loop computations, MadLoop requires dedicated tools to perform the reduction of loop Feynman diagrams using OPP-based and/or TIR approaches.

Which one do you want to install? (this needs to be done only once)
1. cuttools  (OPP) [0711.3596]   : will be installed (required)
2. iregi     (TIR) [1405.0301]   : will be installed (required)
3. ninja     (OPP) [1403.1229]   : will be installed (recommended)
4. collier   (TIR) [1604.06792]  : do not install
5. golem     (TIR) [0807.0605]   : do not install
You can:
 -> hit 'enter' to proceed
 -> type a number to cycle its options
 -> enter the following command:
    {tool_name} [install|noinstall|{prefixed_installation_path}]

If you are unsure about what this question means, just type enter to proceed.
found line : set run_mode 2
This answer is not valid for current question. Keep it for next question and use here default: 0
install ninja
   You are installing 'ninja', please cite ref(s): arXiv:1203.0291, arXiv:1403.1229, arXiv:1604.01363.
Command "import /data/run.mg5" interrupted in sub-command:
"output PROC_madgraph" with error:
PermissionError : [Errno 13] Permission denied: 'installLHAPDF6.sh'
Please report this bug on https://bugs.launchpad.net/mg5amcnlo
More information is found in 'MG5_debug'.
Please attach this file to your report.
```

I suspect this has something to do with loops (`p p > h [QCD]`), but I don't understand how.

**Comment by mhance** [comment]
This should be fixed in the main as of this morning (https://github.com/scipp-atlas/mapyde/commit/fcefd5b49807b29a4db91ff31b2669caeac85dfe) in the MG latest-2.9.10 container (https://github.com/scipp-atlas/mapyde/pkgs/container/mapyde%2Fmadgraph/117177215?tag=latest-2.9.10).  Let me know if this sorts everything out for you, if so we can close this issue.

**Comment by JasonNielsen** [comment]
This works in the newest container, as long as the user knows to 
* use _latest-2.9.10_ instead of _latest_
* use `sm-heft.slha` instead of `sm.slha` or `sm-full.slha`

**Comment by mhance** [comment]
I agree on `latest-2.9.10` instead of `latest`.

I think we only need `sm-heft` when using the `heft` model, not when using loop_sm.  At least I had no problems using just `sm.slha` with loop_sm.  Did you see issues with that?

**Comment by JasonNielsen** [comment]
You are probably right. Particle ID 9000006 is only needed for the HEFT model.

**Comment by mhance** [comment]
Excellent.  I'll close this, but keep the issues coming!
