### ISSUE TITLE
Add heft model to the madgraph-2.9.10 container

### ISSUE THREAD

**Issue by JasonNielsen** [scipp-atlas/mapyde#104]
Could we add the heft model to the madgraph Docker container, so that we can run gluon-gluon fusion production and H&rarr;&gamma;&gamma; decay?

It looks like the mssm_v4.tgz is the only model file downloaded for the madgraph Docker container, according to the [Dockerfile](../blob/main/Dockerfiles/madgraph-2.9.10).

We can get the heft_v4.tgz file in the same way from the [NIU model repository](http://madgraph.physics.illinois.edu/Downloads/models/).

**Comment by mhance** [comment]
Yes, this is a good idea, I can try to do this tonight even.  Do you have an example run/param card I can use to test that it's working?

**Comment by JasonNielsen** [comment]
> Do you have an example run/param card I can use to test that it's working?

Yes, I will submit a merge request now.

**Comment by JasonNielsen** [comment]
I submitted MR #105.

**Comment by mhance** [comment]
I've added heft to 2.9.10 (not heft_v4, just heft), and checked that one can use it.  Required lots of subtle changes in the dockerfile (https://github.com/scipp-atlas/mapyde/blob/main/Dockerfiles/madgraph-2.9.10) but should be working now.  The current version (as of this morning) should also support loop_sm.
