### ISSUE TITLE
Images inacessible

### ISSUE THREAD

**Issue by sambklein** [scipp-atlas/mapyde#142]
The docker images stored under ghcr.io/scipp-atlas/mario-mapyde/ are not publicly available and so can't be pulled. This is relevant for the tutorial (https://scipp-atlas.github.io/mapyde-tutorial/RealWorldExample.html) where these images are used by default, but also for accessing the image with cuda

**Comment by kratsg** [comment]
Thanks for the report -- this is fixed. The problem was the tutorial was on v0.4.6 instead of v0.5.0 where we renamed the repository from `mario-mapyde` to `mapyde` so the locations were changed. This should be fixed now if you would like to check it again.
